name: Extract PDF Text

on:
  workflow_dispatch:
  push:
    paths:
      - 'manuals/**.pdf'

jobs:
  extract-text:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pdfplumber

    - name: Extract text from PDFs
      run: |
        mkdir -p extracted_text
        
        for pdf in manuals/*.pdf; do
          echo "Processing: $pdf"
          filename=$(basename "$pdf" .pdf)
          
          python -c "
import pdfplumber
import json
import re

output = []
try:
    with pdfplumber.open('$pdf') as pdf:
        for i, page in enumerate(pdf.pages[:10]):  # First 10 pages only
            text = page.extract_text()
            if text:
                clean_text = re.sub(r'\s+', ' ', text).strip()
                if len(clean_text) > 100:
                    output.append({
                        'file': '$filename.pdf',
                        'page': i + 1,
                        'text': clean_text[:500] + '...' if len(clean_text) > 500 else clean_text
                    })
    
    with open(f'extracted_text/{filename}.json', 'w') as f:
        json.dump(output, f, indent=2)
        
    print(f'Saved {len(output)} segments from {filename}.pdf')
    
except Exception as e:
    print(f'Error with {filename}: {e}')
          "
        done

    - name: Create combined JSON
      run: |
        python -c "
import json
import glob

all_data = []
for f in glob.glob('extracted_text/*.json'):
    try:
        with open(f) as file:
            data = json.load(file)
            all_data.extend(data)
    except:
        continue

with open('manuals/manuals.json', 'w') as f:
    json.dump(all_data, f, indent=2)

print(f'Total segments: {len(all_data)}')
        "

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add extracted_text/ manuals/manuals.json
        git commit -m "Extract PDF text" || echo "No changes"
        git push
