async function loadManuals() {
  const loadingEl = document.getElementById('loading');
  const container = document.getElementById('container');
  
  try {
    console.log('Загрузка мануалов из GitHub...');
    const response = await fetch(`https://api.github.com/repos/${REPO}/contents/${FOLDER}`);
    
    if(!response.ok) {
      throw new Error(`Ошибка GitHub: ${response.status} ${response.statusText}`);
    }
    
    const data = await response.json();
    console.log('Получены данные:', data);
    
    const pdfs = data.filter(f => f.type === 'file' && f.name.toLowerCase().endsWith('.pdf'));
    console.log('Найдено PDF-файлов:', pdfs.length);
    
    if(pdfs.length === 0){
      container.innerHTML = '<div class="error">PDF-файлы не найдены</div>';
      loadingEl.style.display = 'none';
      return;
    }
    
    loadingEl.style.display = 'none';
    
    pdfs.forEach(file => {
      const name = file.name.replace('.pdf','').replace(/_/g,' ');
      const rawUrl = `https://raw.githubusercontent.com/${REPO}/main/${FOLDER}/${encodeURIComponent(file.name)}`;
      
      console.log('Добавляем файл:', name, rawUrl);
      
      const card = document.createElement('div');
      card.className = 'manual';
      card.innerHTML = `<h2>${name}</h2>
                        <div class="manual-buttons">
                          <button class="btn-ai" onclick="openManualChat('${name}', '${rawUrl}')"><i class="fa-solid fa-brain"></i> AI</button>
                          <button class="btn-open" onclick="openPDF('${rawUrl}')"><i class="fas fa-book"></i> ОТКРЫТЬ</button>
                        </div>`;
      container.appendChild(card);
    });
    
  } catch(err) {
    console.error('Ошибка загрузки:', err);
    loadingEl.style.display = 'none';
    container.innerHTML = `
      <div class="error">
        <h3>Ошибка загрузки мануалов</h3>
        <p>${err.message}</p>
        <p>Проверьте: 
          <ul>
            <li>Доступ к GitHub API</li>
            <li>Публичный доступ к репозиторию</li>
            <li>Сеть и CORS</li>
          </ul>
        </p>
      </div>
    `;
  }
}
