# .github/workflows/extract.yml
name: Extract PDF Text

on:
  push:
    paths:
      - 'manuals/**.pdf'

jobs:
  extract-text:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber

    - name: Extract text from PDFs
      run: |
        mkdir -p extracted_text
        for pdf in manuals/*.pdf; do
          filename=$(basename "$pdf" .pdf)
          python -c "
import pdfplumber
import json
import re

text_content = []
with pdfplumber.open('$pdf') as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if text:
            # Clean up text
            text = re.sub(r'\s+', ' ', text)
            text_content.append(text)

# Save extracted text
with open(f'extracted_text/{filename}.txt', 'w') as f:
    f.write('\n'.join(text_content))

print(f'Extracted text from {filename}.pdf')
          "
        done

    - name: Commit and push extracted text
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add extracted_text/
        git commit -m "Add extracted text from PDFs" || echo "No changes to commit"
        git push
