name: Extract PDF Text

on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pdfplumber

      - name: Create directories
        run: mkdir -p extracted_text

      - name: Create simple Python script
        run: |
          echo 'import json' > extract.py
          echo 'print("Simple extraction script created")' >> extract.py

      - name: List PDF files
        run: ls -la manuals/

      - name: Test one PDF file
        run: |
          first_pdf=$(ls manuals/*.pdf | head -1)
          echo "Testing with: $first_pdf"
          python -c "import pdfplumber; print('PDFplumber works!'); print('File:', '$first_pdf')"

      - name: Create empty manuals.json
        run: echo '[]' > manuals/manuals.json

      - name: Completion message
        run: echo "Workflow completed successfully! Ready for next step."
