name: Extract PDF Text

on: 
  workflow_dispatch
  push:
    paths:
      - 'manuals/**.pdf'

jobs:
  extract:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install pdfplumber
      run: pip install pdfplumber
      
    - name: Extract PDF text
      run: |
        mkdir -p extracted_text
        
        for pdf in manuals/*.pdf; do
          echo "Processing: $pdf"
          python -c "
import pdfplumber
import json
import re

texts = []
try:
    with pdfplumber.open('$pdf') as pdf:
        for i, page in enumerate(pdf.pages[:5]):
            text = page.extract_text()
            if text:
                clean_text = re.sub(r'\s+', ' ', text).strip()
                if len(clean_text) > 50:
                    texts.append({
                        'file': '$pdf',
                        'page': i+1,
                        'text': clean_text[:300]
                    })
    
    if texts:
        filename = '$pdf'.split('/')[-1].replace('.pdf', '')
        with open(f'extracted_text/{filename}.json', 'w') as f:
            json.dump(texts, f, indent=2)
        print(f'✓ Extracted {len(texts)} pages from $pdf')
    else:
        print(f'✗ No text found in $pdf')
        
except Exception as e:
    print(f'Error with $pdf: {e}')
          "
        done
