name: Extract PDF Text

on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pdfplumber

      - name: Create extraction script
        run: |
          cat > extract.py << "EOL"
import pdfplumber
import json
import os
import glob

# Создаем папку для результатов
os.makedirs('extracted_text', exist_ok=True)

all_data = []
pdf_files = glob.glob('manuals/*.pdf')

print(f"Найдено PDF файлов: {len(pdf_files)}")

for pdf_path in pdf_files:
    filename = os.path.basename(pdf_path)
    print(f"Обрабатывается: {filename}")
    
    try:
        with pdfplumber.open(pdf_path) as pdf:
            if pdf.pages:
                # Берем текст с первой страницы
                page = pdf.pages[0]
                text = page.extract_text()
                
                if text:
                    # Очищаем и обрезаем текст
                    clean_text = ' '.join(text.split())
                    if len(clean_text) > 100:
                        text_data = {
                            'file': filename,
                            'page': 1,
                            'text': clean_text[:300] + '...' if len(clean_text) > 300 else clean_text
                        }
                        all_data.append(text_data)
                        print(f"✓ Извлечен текст из {filename}")
                    else:
                        print(f"✗ Мало текста в {filename}")
                else:
                    print(f"✗ Не удалось извлечь текст из {filename}")
            else:
                print(f"✗ Нет страниц в {filename}")
                
    except Exception as e:
        print(f"✗ Ошибка при обработке {filename}: {e}")

# Сохраняем результаты
with open('manuals/manuals.json', 'w', encoding='utf-8') as f:
    json.dump(all_data, f, indent=2, ensure_ascii=False)

print(f"Готово! Извлечено {len(all_data)} текстовых сегментов")
EOL

      - name: Run text extraction
        run: python extract.py

      - name: Show results
        run: |
          echo "=== РЕЗУЛЬТАТЫ ==="
          if [ -f "manuals/manuals.json" ]; then
            echo "Текстовых сегментов: $(python -c \"import json; f=open('manuals/manuals.json'); data=json.load(f); print(len(data)); f.close()\")"
            echo "Последний файл: $(python -c \"import json; f=open('manuals/manuals.json'); data=json.load(f); print(data[-1]['file'] if data else 'Нет данных'); f.close()\")"
          else
            echo "Файл manuals.json не создан"
          fi
