name: Extract PDF Text

on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pdfplumber

      - name: Create directories
        run: mkdir -p extracted_text

      - name: Create simple extractor script
        run: |
          # Создаем простой Python скрипт
          echo 'import json' > extract_simple.py
          echo 'import glob' >> extract_simple.py
          echo 'print("Simple extractor ready")' >> extract_simple.py

      - name: Test PDF files
        run: |
          echo "Available PDF files:"
          ls -la manuals/*.pdf
          echo ""
          echo "Testing PDF extraction..."
          first_pdf=$(ls manuals/*.pdf | head -1)
          python -c "
import pdfplumber
try:
    with pdfplumber.open('$first_pdf') as pdf:
        if pdf.pages:
            text = pdf.pages[0].extract_text()
            if text:
                print('SUCCESS: Text extracted from first PDF')
                print('First 100 chars:', text[:100] + '...')
            else:
                print('NO TEXT: Could not extract text')
        else:
            print('NO PAGES: PDF has no pages')
except Exception as e:
    print('ERROR:', str(e))
          "

      - name: Create manuals.json
        run: echo '[{"test": "data"}]' > manuals/manuals.json

      - name: Complete
        run: echo "Workflow completed successfully! Next step: add full extraction."
